### ISSUE TITLE
[Bug]: Latex in lunarvim is a joke

### ISSUE THREAD

**Issue by ahmedkhalf** [LunarVim/LunarVim#1257]
### Problem description

First, why is lunarvim creating parenthesis? In latex, we use curly brackets after documentclass...

https://user-images.githubusercontent.com/36672196/128592716-54761e2c-30e7-4ff9-b73b-41cd338162e0.mp4

Also, it seems LSP activation for .tex files is hit or miss, sometimes it works, and sometimes it doesn't activate:

![image](https://user-images.githubusercontent.com/36672196/128592848-fdc2ed81-6296-40bc-b096-47a9596afcc5.png)

### Check the following

- [x] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/nvim/ftplugin/)
- [X] I checked the options (~/.config/nvim/lv-config.lua)
- [X] The programs specified by the config are installed

### LunarVim version

Lunarvim Master Branch, Latest commit

### Neovim version (>= 0.5)

v0.6.0-dev+108-g5130bc071

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by rebuilt** [comment]
Can you list the output of `:set filetype?` when it registers the correct filetype vs the incorrect filetype please.  The defaults provided by lspconfig are `    filetypes = { "tex", "bib" }`  but maybe we need to add `latex` to the filetype list?

The parenthesis is provided by the autopairs plugin.  As far as I know, it doesn't easily let you disable by filetype.  
This is what is provides
```
 require('nvim-autopairs').disable()
  require('nvim-autopairs').enable()
  require('nvim-autopairs').remove_rule('(')-- remove rule (
  require('nvim-autopairs').clear_rules() -- clear all rule
```

**Comment by ahmedkhalf** [comment]
filetype is plaintex

**Comment by ahmedkhalf** [comment]
Also, I would like a way to delete all the existing latex snippets, and create my own.

**Comment by rebuilt** [comment]
You can create your own snippets by following the [vsnip guide](https://github.com/hrsh7th/vim-vsnip#3-create-your-own-snippet)
That's the plugin that provides snippet functionality.

It relies on friendly snippets to provide the [snippet library](https://github.com/rafamadriz/friendly-snippets). It stores it's library in 
`.local/share/lunarvim/site/pack/packer/opt/friendly-snippets/snippets`.  But I think if you delete this folder it will get recreated each time update the plugin.

**Comment by ChristianChiarulli** [comment]
We could support disabling friendly snippets, also LunarVim doesn't really claim to have first class latex support, although it will be a priority in the future.

**Comment by ahmedkhalf** [comment]
Okay just to clear things up, in order to close this issue we would have to:

1. Add "plaintex" filetype to LSP.
2. Provide a way to disable the automatic parenthesis only in latex because latex does not use parenthesis but rather curly brackets.
3. Provide a way to disable friendly snippets relating to certain filetypes like latex - my guess is that this needs to be done inside vim-vsnip itself. (Although adding functionality to disable friendly snippets as a whole is fine, this is not the goal of the issue, but rather I only want to disable them for latex)

**Comment by rebuilt** [comment]
>     2. Provide a way to disable the automatic parenthesis only in latex because latex does not use parenthesis but rather curly brackets.
Is the parenthesis rule the only problematic one?

We can set up and autocommand on the latex filetype to disable the parenthesis
```
  require('nvim-autopairs').remove_rule('(')-- remove rule (
```
>     3. Provide a way to disable friendly snippets relating to certain filetypes like latex - my guess is that this needs to be done inside vim-vsnip itself. (Although adding functionality to disable friendly snippets as a whole is fine, this is not the goal of the issue, but rather I only want to disable them for latex)

Not sure how to turn it off just for a given filetype.  Suggestions welcome.

**Comment by abzcoding** [comment]
@ahmedkhalf pull the latest changes, 1 and 2 should be fixed

**Comment by abzcoding** [comment]
nice title btw, i was eager to help you 😏

**Comment by ahmedkhalf** [comment]
Okay, so both 1 and 2 have been successfully fixed! tnx!

But I have one small picky issue regarding compe in general:
![image](https://user-images.githubusercontent.com/36672196/128637812-2cb0e563-519f-47ce-856e-93966d90993d.png)

When I press enter here, it would be great if it just closes the popup menu rather than creating a new line.

> Not sure how to turn it off just for a given filetype. Suggestions welcome.

My suggestion is that this could be fixed by the vim-vsnip devs as they handle the reading of the json snippets. So perhaps opening an issue on their repo would be appropriate.

**Comment by abzcoding** [comment]
> Okay, so both 1 and 2 have been successfully fixed! tnx!
> 
> But I have one small picky issue regarding compe in general:
> ![image](https://user-images.githubusercontent.com/36672196/128637812-2cb0e563-519f-47ce-856e-93966d90993d.png)
> 
> When I press enter here, it would be great if it just closes the popup menu rather than creating a new line.
> 
> > Not sure how to turn it off just for a given filetype. Suggestions welcome.
> 
> My suggestion is that this could be fixed by the vim-vsnip devs as they handle the reading of the json snippets. So perhaps opening an issue on their repo would be appropriate.

plz pull the latest changes, the compe thingy should be fixed as well

**Comment by ahmedkhalf** [comment]
I'm sorry, but it seems that the fix for 2 is inconsistent, before even pulling the latest changes I opened my tex file and the same behavior from the video occurred again. Pulling doesn't seem to fix too.

**Comment by abzcoding** [comment]
> I'm sorry, but it seems that the fix for 2 is inconsistent, before even pulling the latest changes I opened my tex file and the same behavior from the video occurred again. Pulling doesn't seem to fix too.

can you run these
```vim
:echom &filetype
:LspInfo
```
also
`~/.cache/nvim/lsp.log` can be helpful 🥺

**Comment by abzcoding** [comment]
also can you hop on discord so we can chat about it in realtime 😅

**Comment by ahmedkhalf** [comment]
echom &filetype: `tex`
:LspInfo:
```
Configured servers: html, python, null-ls, json, texlab, bash, latex, lua, css, go
Neovim logs at: /home/ahmedk/.cache/nvim/lsp.log

1 client(s) attached to this buffer: texlab

  Client: texlab (id: 1 pid: 56047)
  	root:      /home/ahmedk/Documents/UOFT/Course Notes/ArriveReady
  	filetypes: tex, bib
  	cmd:       /home/ahmedk/.local/share/nvim/lspinstall/latex/texlab
  	autostart: True

1 active client(s): 

  Client: texlab (id: 1 pid: 56047)
  	root:      /home/ahmedk/Documents/UOFT/Course Notes/ArriveReady
  	filetypes: tex, bib
  	cmd:       /home/ahmedk/.local/share/nvim/lspinstall/latex/texlab
  	autostart: True
```
The first thing I notice here, is null-ls isn't attached.

~/.cache/nvim/lsp.log
Nothing relevant to tex, all logs are regarding python.

> also can you hop on discord so we can chat about it in realtime sweat_smile

Okay, will do now :+1: . Username: Itwist#7732

**Comment by abzcoding** [comment]
## problem description for anybody that wants to help
when you open a `tex` file directly everything is fine, but if you open it using `telescope` then the `(` issue thingy is there
we have this code
```lua
if package.loaded["compe"] then
  local map_complete_optional = vim.bo.filetype ~= "tex"
  require("nvim-autopairs.completion.compe").setup {
    map_cr = true, --  map <CR> on insert mode
    map_complete = map_complete_optional, -- it will auto insert `(` after select function or method item
  }
end
```
but the problem is that when you open a file through `telescope` this function has already been called and the `map_complete` has been set to `true`

**Comment by rebuilt** [comment]
Waiting for this commit to merge so we can fix the automatic `(` insertion in latex files.  https://github.com/windwp/nvim-autopairs/pull/131

**Comment by abzcoding** [comment]
fixed via #1566
