### ISSUE TITLE
[Bug]: nvim-tree unable to locate opened file

### ISSUE THREAD

**Issue by angryheng** [LunarVim/LunarVim#2014]
### Problem description

I open a  file and when I press <Leader>e, it is not located in the file

### LunarVim version

rolling

### Neovim version (>= 0.5)

0.6

### Screenshots

![bug](https://user-images.githubusercontent.com/28853495/144213635-3acfe464-5e70-458f-9bc9-2f6825762c8a.gif)

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

**Comment by kylo252** [comment]
Please open that file again, and copy the output of 
```vim
:echo getcwd()
```

**Comment by angryheng** [comment]
@kylo252 in the root directory

**Comment by xeluxee** [comment]
https://github.com/kyazdani42/nvim-tree.lua/issues/783

**Comment by xeluxee** [comment]
> Please open that file again, and copy the output of
> 
> ```viml
> :echo getcwd()
> ```

It prints my home directory because LSP root isn't available when running in single file mode

**Comment by kylo252** [comment]
> It prints my home directory because LSP root isn't available when running in single file mode

That's related to `project.nvim`. You can tell it to ignore certain servers if you know that you always run them for single-files.

**Comment by xeluxee** [comment]
Update: https://github.com/kyazdani42/nvim-tree.lua/issues/783#issuecomment-983819095
I think that's not LSP related

**Comment by Leiyi548** [comment]
@angryheng 
set lvim.builtin.project.manual_mode = true
Project.nvim will not automatically change your directory, but you need to do it manually
This plug-in will automatically change your root directory

**Comment by xeluxee** [comment]
> set lvim.builtin.project.manual_mode = true

It doesn't work for me, I still have to press `R` to reload after `:NvimTreeFindFile`
I think that's a NvimTree problem...

**Comment by angryheng** [comment]
@Leiyi548 thanks, but it dosen't work for me

**Comment by kola-web** [comment]
lvim.builtin.project.active = false

**Comment by xeluxee** [comment]
> lvim.builtin.project.active = false

This doesn't work for me, the issue still remains

**Comment by kola-web** [comment]
lvim.builtin.project.active = false
try it

**Comment by xeluxee** [comment]
> lvim.builtin.project.active = false try it

I've tried it but still it doesn't work, I don't think project.nvim is related because it's a matter of reloading buffer content. Indeed when I press `R` it displays files correctly

**Comment by xeluxee** [comment]
The problem has been solved by https://github.com/kyazdani42/nvim-tree.lua/pull/836
Now we can update NvimTree commit and close this issue

**Comment by angryheng** [comment]
@xeluxee Thanks a lot, but I updated NvimTree and the problem still persists and I still need to press R

**Comment by xeluxee** [comment]
@angryheng if you updated plugins trough Packer you aren't using latest NvimTree version because all the core plugins are pinned.
I've tried the latest version updating manually and it works

We should wait for @kylo252 or someone else to bump commits

**Comment by angryheng** [comment]
@xeluxee thanks,  how to update manually

**Comment by angryheng** [comment]
@xeluxee I ran the packupdate command

**Comment by xeluxee** [comment]
@angryheng just pull latest LunarVim from rolling branch
Now thanks to #2079 NvimTree can be updated

**Comment by xeluxee** [comment]
And I think this issue can be closed now
