### ISSUE TITLE
offset_encoding: expected string, got nil

### ISSUE THREAD

**Issue by rafa-acioly** [LunarVim/LunarVim#2191]
### Problem description

When I try to use the LSP suggestion an error shows up.

### LunarVim version

7125e2b

### Neovim version (>= 0.6)

NVIM v0.7.0-dev+905-gfcf5dd34f Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Operating system/version

ubuntu 20.04

### Affected language servers

gopls

### Steps to reproduce

1. open any code file
2. start typing to get the suggestion
3. press enter on the suggested dropdown

### Actual behavior

The LSP suggestions are showing up and I can choose it by pressing `TAB` but if I press `ENTER` on the suggestion the error appears.

### Expected behavior

When I press enter i expect that the code is completed by the suggestionI

### log and support info

```shell
LSP LOG

[ERROR][2022-01-18 11:45:01] ...lsp/handlers.lua:443	'2022/01/18 11:45:01 unable to compute positions for type errors: no parsed file for  in rafa-acioly/carbon\n\tpackage="rafa-acioly/carbon"\n'
[ERROR][2022-01-18 11:45:01] ...lsp/handlers.lua:443	'2022/01/18 11:45:01 unable to compute positions for type errors: no parsed file for  in rafa-acioly/carbon [rafa-acioly/carbon.test]\n\tpackage="rafa-acioly/carbon [rafa-acioly/carbon.test]"\n'
[ERROR][2022-01-18 11:45:01] ...lsp/handlers.lua:443	'2022/01/18 11:45:01 unable to compute positions for type errors: no parsed file for  in rafa-acioly/carbon\n\tpackage="rafa-acioly/carbon"\n'
[ERROR][2022-01-18 11:45:01] ...lsp/handlers.lua:443	'2022/01/18 11:45:01 unable to compute positions for type errors: no parsed file for  in rafa-acioly/carbon [rafa-acioly/carbon.test]\n\tpackage="rafa-acioly/carbon [rafa-acioly/carbon.test]"\n'
[ERROR][2022-01-18 11:45:25] ...lsp/handlers.lua:443	'2022/01/18 11:45:25 unable to compute positions for type errors: no parsed file for  in rafa-acioly/carbon\n\tpackage="rafa-acioly/carbon"\n'
[ERROR][2022-01-18 11:45:25] ...lsp/handlers.lua:443	'2022/01/18 11:45:25 unable to compute positions for type errors: no parsed file for  in rafa-acioly/carbon [rafa-acioly/carbon.test]\n\tpackage="rafa-acioly/carbon [rafa-acioly/carbon.test]"\n'
[ERROR][2022-01-18 11:45:25] ...lsp/handlers.lua:443	"2022/01/18 11:45:25 no completions found: %!w(getting file for Completion: <nil> (package completions: invalid position for package completion: cursor in non-matching ident))\n\tposition={0 2}\n"
[ERROR][2022-01-18 11:45:25] ...lsp/handlers.lua:443	"2022/01/18 11:45:25 no completions found: %!w(getting file for Completion: <nil> (package completions: invalid position for package completion: cursor in non-matching ident))\n\tposition={0 3}\n"
[ERROR][2022-01-18 11:45:25] ...lsp/handlers.lua:443	'2022/01/18 11:45:25 unable to compute positions for type errors: no parsed file for  in rafa-acioly/carbon\n\tpackage="rafa-acioly/carbon"\n'
[ERROR][2022-01-18 11:45:25] ...lsp/handlers.lua:443	'2022/01/18 11:45:25 unable to compute positions for type errors: no parsed file for  in rafa-acioly/carbon [rafa-acioly/carbon.test]\n\tpackage="rafa-acioly/carbon [rafa-acioly/carbon.test]"\n'
[ERROR][2022-01-18 11:45:26] ...lsp/handlers.lua:443	'2022/01/18 11:45:26 unable to compute positions for type errors: no parsed file for  in rafa-acioly/carbon\n\tpackage="rafa-acioly/carbon"\n'
[ERROR][2022-01-18 11:45:26] ...lsp/handlers.lua:443	'2022/01/18 11:45:26 unable to compute positions for type errors: no parsed file for  in rafa-acioly/carbon [rafa-acioly/carbon.test]\n\tpackage="rafa-acioly/carbon [rafa-acioly/carbon.test]"\n'
[ERROR][2022-01-18 11:45:26] ...lsp/handlers.lua:443	"2022/01/18 11:45:26 no completions found: %!w(getting file for Completion: <nil> (package completions: invalid position for package completion: cursor in non-matching ident))\n\tposition={0 2}\n"
[ERROR][2022-01-18 11:45:26] ...lsp/handlers.lua:443	'2022/01/18 11:45:26 unable to compute positions for type errors: no parsed file for  in rafa-acioly/carbon\n\tpackage="rafa-acioly/carbon"\n'
[ERROR][2022-01-18 11:45:26] ...lsp/handlers.lua:443	'2022/01/18 11:45:26 unable to compute positions for type errors: no parsed file for  in rafa-acioly/carbon [rafa-acioly/carbon.test]\n\tpackage="rafa-acioly/carbon [rafa-acioly/carbon.test]"\n'
[START][2022-01-18 11:46:19] LSP logging initiated
[START][2022-01-18 11:49:55] LSP logging initiated
[ERROR][2022-01-18 11:50:08] ...lsp/handlers.lua:443	'2022/01/18 11:50:08 unable to compute positions for type errors: no parsed file for  in rafa-acioly/carbon\n\tpackage="rafa-acioly/carbon"\n'
[ERROR][2022-01-18 11:50:08] ...lsp/handlers.lua:443	'2022/01/18 11:50:08 unable to compute positions for type errors: no parsed file for  in rafa-acioly/carbon [rafa-acioly/carbon.test]\n\tpackage="rafa-acioly/carbon [rafa-acioly/carbon.test]"\n'
[START][2022-01-18 11:51:19] LSP logging initiated
[ERROR][2022-01-18 11:51:41] ...lsp/handlers.lua:443	'2022/01/18 11:51:41 unable to compute positions for type errors: no parsed file for  in rafa-acioly/carbon\n\tpackage="rafa-acioly/carbon"\n'
[ERROR][2022-01-18 11:51:41] ...lsp/handlers.lua:443	'2022/01/18 11:51:41 unable to compute positions for type errors: no parsed file for  in rafa-acioly/carbon [rafa-acioly/carbon.test]\n\tpackage="rafa-acioly/carbon [rafa-acioly/carbon.test]"\n'


LVIM LOG

11:59:05 [DEBUG] lvim: "loading plugins configuration" file="lvim/lua/lvim/plugin-loader.lua", line=77
11:59:05 [DEBUG] lvim: "Starting LunarVim"            file="share/lunarvim/lvim/init.lua", line=16
11:59:05 [DEBUG] lvim: "Setting up LSP support"       file="lua/lvim/lsp/init.lua", line=130
11:59:05 [DEBUG] lvim: "enabled format-on-save"       file="lua/lvim/core/autocmds.lua", line=78
11:59:05 [DEBUG] lvim: { "master" }                   file="lua/lvim/utils/git.lua", line=31
11:59:05 [DEBUG] lvim: { "fatal: No names found, cannot describe anything." } file="lua/lvim/utils/git.lua", line=27
11:59:06 [DEBUG] lvim: "Checking for formatter overriding for gopls" file="lua/lvim/lsp/init.lua", line=72
```

### Screenshots

![lvim](https://user-images.githubusercontent.com/11068059/149960596-f6f0004c-744b-4c49-a6e0-7b8a627b4058.png)

![Screenshot from 2022-01-18 10-56-53](https://user-images.githubusercontent.com/11068059/149962323-78bc1d77-2834-44c0-a9e3-44dbca396a1c.png)

**Comment by abzcoding** [comment]
Can you try the latest rolled nh branch? 
cc: @kylo252

**Comment by rafa-acioly** [comment]
@abzcoding @kylo252 I've changed the nvim version to v0.6.1 (stable) and is working fine.

**Comment by abzcoding** [comment]
maybe we should change this line in installer to check for `0.6.1` instead of `0.6.0`
https://github.com/LunarVim/LunarVim/blob/56df185b1b9ec9c620e80654d314541beca76f26/utils/installer/install.sh#L173-L177

**Comment by crisidev** [comment]
I have the same error and and I am on rolling with 

```
NVIM v0.7.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-di40hU/neovim-0.7.0~ubuntu1+git202201190048-fcf5dd34f-dd05b3569=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-di40hU/neovim-0.7.0~ubuntu1+git202201190048-fcf5dd34f-dd05b3569/build/config -I/build/neovim-di40hU/neovim-0.7.0~ubuntu1+git202201190048-fcf5dd34f-dd05b3569/src -I/build/neovim-di40hU/neovim-0.7.0~ubuntu1+git202201190048-fcf5dd34f-dd05b3569/.deps/usr/include -I/usr/include -I/build/neovim-di40hU/neovim-0.7.0~ubuntu1+git202201190048-fcf5dd34f-dd05b3569/build/src/nvim/auto -I/build/neovim-di40hU/neovim-0.7.0~ubuntu1+git202201190048-fcf5dd34f-dd05b3569/build/include
Compiled by buildd@lgw01-amd64-059

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by abzcoding** [comment]
@crisidev first off make sure that you are on the latest rolling and also run `:LvimUpdate` that should fix it

**Comment by crisidev** [comment]
I have the same commit as you are and I still seeing the error when I try to complete after:
* `:LvimUpdate`
* `:LvimCacheReset`
* `:PackerSync`

**Comment by abzcoding** [comment]
a screenshot would be appreciated

**Comment by abzcoding** [comment]
@crisidev sadly we can't do much about this issue inside lunarvim since it comes from `telescope` or `nvim-cmp` or some other plugin, there is a temporary fix though

for example, you can change this function inside `/usr/local/share/nvim/runtime/lua/vim/lsp/util.lua`:
(the util.lua in that shows up with the error)
```lua
-- line 365
function M.apply_text_edits(text_edits, bufnr, offset_encoding)
  if offset_encoding == nil then -- these 3 lines would fix that issue
    offset_encoding = "utf-16"
  end
  validate {
    text_edits = { text_edits, 't', false };
    bufnr = { bufnr, 'number', false };
    offset_encoding = { offset_encoding, 'string', false };
  }
  -- ...
```
to make it never would be `nil`

**Comment by abzcoding** [comment]
Can you guys update to the latest lunarvim and let me know if the issue still exists or not?

**Comment by crisidev** [comment]
The latest changes in LunarVim fixed this for me with neovim 0.7.0-dev! Thanks a million @abzcoding
