### ISSUE TITLE
Error executing luv callback

### ISSUE THREAD

**Issue by threeaccents** [LunarVim/LunarVim#2460]
### Problem description

# steps to reproduce.

1. Install lunarvim
2. open the lunarvim config in lunarvim. `lvim ~/.config/lvim/config.lua`

### LunarVim version

f92a0d610c1ee899ec8acb091130f2a5eec22812

### Neovim version (>= 0.6.1)

NVIM v0.7.0-dev+1446-g18152cf6f

### Operating system/version

Fedora 35 using Sway

### Relevant log output

```shell
Error executing luv callback:                                                                                                                                                                  
...ite/pack/packer/opt/gitsigns.nvim/lua/gitsigns/async.lua:75: The coroutine failed with this message: ...ccents/.local/share/lunarvim/lvim/lua/lvim/impatient.lua:206: E5560: nvim_get_option
 must not be called in a lua loop callback                                                                                                                                                     
stack traceback:                                                                                                                                                                               
        [C]: in function 'require'                                                                                                                                                             
        ...site/pack/packer/opt/gitsigns.nvim/lua/gitsigns/diff.lua:8: in function 'run_diff'                                                                                                  
        ...e/pack/packer/opt/gitsigns.nvim/lua/gitsigns/manager.lua:221: in function 'fn'                                                                                                      
        .../pack/packer/opt/gitsigns.nvim/lua/gitsigns/debounce.lua:71: in function 'update'                                                                                                   
        ...rvim/site/pack/packer/opt/gitsigns.nvim/lua/gitsigns.lua:296: in function 'attach0'                                                                                                 
        ...rvim/site/pack/packer/opt/gitsigns.nvim/lua/gitsigns.lua:344: in function 'attach'                                                                                                  
        ...rvim/site/pack/packer/opt/gitsigns.nvim/lua/gitsigns.lua:567: in function <...rvim/site/pack/packer/opt/gitsigns.nvim/lua/gitsigns.lua:505>                                         
stack traceback:                                                                                                                                                                               
        [C]: in function 'error'                                                                                                                                                               
        ...ite/pack/packer/opt/gitsigns.nvim/lua/gitsigns/async.lua:75: in function 'callback'                                                                                                 
        .../site/pack/packer/opt/gitsigns.nvim/lua/gitsigns/git.lua:183: in function 'callback'                                                                                                
        ...ack/packer/opt/gitsigns.nvim/lua/gitsigns/subprocess.lua:66: in function <...ack/packer/opt/gitsigns.nvim/lua/gitsigns/subprocess.lua:52>
```

**Comment by diningPhilosopher64** [comment]
Facing similar issue on Ubuntu 20.04 and Debian 11.  

I already had nvim with its configs in both the above systems and thought some kind of conflict between lunarvim and nvim is causing this issue.

Tried in a fresh `ubuntu:latest`  docker container. Still the same issue as above with the exact same error log.

This issue shows up everytime I try to launch lunarvim.

One highlight would be lunarvim works as expected after that ie. after pressing ENTER.

**Comment by abzcoding** [comment]
this is fixed in `rolling`

**Comment by abzcoding** [comment]
@kylo252 we might wanna merge `rolling` into `master`

**Comment by threeaccents** [comment]
@abzcoding I just tried this on rolling and the same error persists. Now with a longer error log though.

```bash
rror executing luv callback:                                                                                                                                                                  
...ite/pack/packer/opt/gitsigns.nvim/lua/gitsigns/async.lua:75: The coroutine failed with this message: ...site/pack/packer/opt/gitsigns.nvim/lua/gitsigns/diff.lua:8: module 'gitsigns.diff_in
t' not found:                                                                                                                                                                                  
        no field package.preload['gitsigns.diff_int']No cache entry                                                                                                                            
        no file './gitsigns/diff_int.lua'                                                                                                                                                      
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/gitsigns/diff_int.lua'                                                                                     
        no file '/usr/local/share/lua/5.1/gitsigns/diff_int.lua'                                                                                                                               
        no file '/usr/local/share/lua/5.1/gitsigns/diff_int/init.lua'                                                                                                                          
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/gitsigns/diff_int.lua'                                                                                                
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/gitsigns/diff_int/init.lua'                                                                                           
        no file '/home/threeaccents/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/gitsigns/diff_int.lua'                                                                              
        no file '/home/threeaccents/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/gitsigns/diff_int/init.lua'                                                                         
        no file '/home/threeaccents/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/gitsigns/diff_int.lua'                                                                     
        no file '/home/threeaccents/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/gitsigns/diff_int/init.lua'                                                                
        no file './gitsigns/diff_int.so'                                                                                                                                                       
        no file '/usr/local/lib/lua/5.1/gitsigns/diff_int.so'                                                                                                                                  
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/gitsigns/diff_int.so'                                                                                                   
        no file '/usr/local/lib/lua/5.1/loadall.so'                                                                                                                                            
        no file '/home/threeaccents/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/gitsigns/diff_int.so'                                                                                 
        no file './gitsigns.so'                                                                                                                                                                
        no file '/usr/local/lib/lua/5.1/gitsigns.so'                                                                                                                                           
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/gitsigns.so'                                                                                                            
        no file '/usr/local/lib/lua/5.1/loadall.so'                                                                                                                                            
        no file '/home/threeaccents/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/gitsigns.so'                                                                                          
stack traceback:                                                                                                                                                                               
        [C]: in function 'require'                                                                                                                                                             
        ...site/pack/packer/opt/gitsigns.nvim/lua/gitsigns/diff.lua:8: in function 'run_diff'                                                                                                  
        ...e/pack/packer/opt/gitsigns.nvim/lua/gitsigns/manager.lua:221: in function 'fn'                                                                                                      
        .../pack/packer/opt/gitsigns.nvim/lua/gitsigns/debounce.lua:71: in function 'update'                                                                                                   
        ...rvim/site/pack/packer/opt/gitsigns.nvim/lua/gitsigns.lua:296: in function 'attach0'                                                                                                 
        ...rvim/site/pack/packer/opt/gitsigns.nvim/lua/gitsigns.lua:344: in function 'attach'                                                                                                  
        ...rvim/site/pack/packer/opt/gitsigns.nvim/lua/gitsigns.lua:567: in function <...rvim/site/pack/packer/opt/gitsigns.nvim/lua/gitsigns.lua:505>                                         
stack traceback:                                                                                                                                                                               
        [C]: in function 'error'                                                                                                                                                               
        ...ite/pack/packer/opt/gitsigns.nvim/lua/gitsigns/async.lua:75: in function 'callback'                                                                                                 
        .../site/pack/packer/opt/gitsigns.nvim/lua/gitsigns/git.lua:183: in function 'callback'                                                                                                
        ...ack/packer/opt/gitsigns.nvim/lua/gitsigns/subprocess.lua:66: in function <...ack/packer/opt/gitsigns.nvim/lua/gitsigns/subprocess.lua:52>           
```

**Comment by abzcoding** [comment]
@threeaccents please run `:LvimUpdate` after switching to `rolling` and reopen LV, if the issue still was there do a `:LvimCacheReset` to make sure nothing is cached

**Comment by abzcoding** [comment]
i had the same issue this morning, but  [this commit](https://github.com/LunarVim/LunarVim/pull/2448/commits/bc0bb372aa648ee12366ceb3d1f39e04c8ec246e) fixed it
which uses this -> https://github.com/lewis6991/gitsigns.nvim/commit/f2e9e30c3e95ccc05ff5b4984e5a07f264198f45

**Comment by threeaccents** [comment]
@abzcoding Still the same error persists after running the commands you recommended. I went ahead also and uninstalled lvim and installed it again but this did not make the error disappear. Let me know if there is anything else I can show/do to help with debugging.

**Comment by abzcoding** [comment]
> @abzcoding Still the same error persists after running the commands you recommended. I went ahead also and uninstalled lvim and installed it again but this did not make the error disappear. Let me know if there is anything else I can show/do to help with debugging.

can you run
```shell
git -C ~/.local/share/lunarvim/lvim rev-parse HEAD
```

**Comment by abzcoding** [comment]
and also
```shell
git -C ~/.local/share/lunarvim/site/pack/packer/opt/gitsigns.nvim rev-parse HEAD
```

**Comment by threeaccents** [comment]
Okay so I quit my tmux session and started a new one and the error did go away.

**Comment by abzcoding** [comment]
> Okay so I quit my tmux session and started a new one and the error did go away. Sorry for the false alarm. And thank you for the quick help!

no worries mate 😅 
yeah i think we should probably merge `rolling` into `master` or at least bump the `gitsigns` plugin version in it

**Comment by diningPhilosopher64** [comment]
I guess, I'll wait for the merge to go through and make a fresh install. Thanks for your input @abzcoding !

**Comment by momadacoding** [comment]
have the same issue with latest lvim
