### ISSUE TITLE
rolling branch installation script hangs, can't run LunarVim

### ISSUE THREAD

**Issue by thiagodebastos** [LunarVim/LunarVim#2466]
## Context

This morning I attempted to update LunarVim like I usually do, via `:LunarVim Update`, however I received an error, and then couldn't find the lunarvim repo folder, usually in `~/.local/share/lunarvim/lvim`.

It seems like the process fails after moving the `lvim` repo folder to `~/.config/lvim.old`.

## Steps to reproduce behaviour:

1. run `LV_BRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh)`

## Result:

Install script hangs:

```
Installing LunarVim shim
starting LunarVim bin-installer
bash ./utils/installer/install_bin.sh
You can start LunarVim by running: /Users/thiago/.local/bin/lvim
Preparing Packer setup
Error detected while processing /Users/thiago/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: .../thiago/.local/share/lunarvim/lvim/lua/lvim/core/cmp.lua:236: attempt to index field 'window' (a nil value)
stack traceback:
	.../thiago/.local/share/lunarvim/lvim/lua/lvim/core/cmp.lua:236: in function 'config'
	...ocal/share/lunarvim/lvim/lua/lvim/core/builtins/init.lua:24: in function 'config'
	...iago/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:32: in function 'init'
	...thiago/.local/share/lunarvim/lvim/lua/lvim/bootstrap.lua:104: in function 'init'
	/Users/thiago/.local/share/lunarvim/lvim/init.lua:8: in main chunkError detected while processing command line:
E492: Not an editor command: PackerSync
```

## Expected

LunarVim installs/updates without errors.

### LunarVim version

N/A cannot load lunarvim at all

### Neovim version (>= 0.6.1)

NVIM v0.7.0-dev+1453-g8486c87e5 Build type: Release LuaJIT 2.1.0-beta3 Compiled by thiago@Thiagos-MBPM1-2.local  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-8486c87/share/nvim"

### Operating system/version

macOS 11.5

### Relevant log output

```shell
:messages

Error detected while processing /Users/thiago/.local/share/lunarvim/lvim/init.lua:
E5113: Error while calling lua chunk: .../thiago/.local/share/lunarvim/lvim/lua/lvim/core/cmp.lua:236: attempt to index field 'window' (a nil value)
stack traceback:
        .../thiago/.local/share/lunarvim/lvim/lua/lvim/core/cmp.lua:236: in function 'config'
        ...ocal/share/lunarvim/lvim/lua/lvim/core/builtins/init.lua:24: in function 'config'
        ...iago/.local/share/lunarvim/lvim/lua/lvim/config/init.lua:32: in function 'init'
        ...thiago/.local/share/lunarvim/lvim/lua/lvim/bootstrap.lua:104: in function 'init'
        /Users/thiago/.local/share/lunarvim/lvim/init.lua:8: in main chunk

:checkhealth
everything passes
```

**Comment by JCallicoat** [comment]
The rolling branch was just merged into master and the same thing is happening there for new installs or existing installs with :LvimUpdate. The problem appears to come from commit 332e974b53.

**Comment by JCallicoat** [comment]
It looks like upstream rolled back a breaking change in https://github.com/hrsh7th/nvim-cmp/issues/899

If I change the commit hash in `snapshots/default.json` to the latest for nvim-cmp and run `lvim +LvimSyncCorePlugins` is seems to be working again.

```
    "nvim-cmp": {
      "commit": "b5433f9"
    },
```

**Comment by abzcoding** [comment]
it should be fixed now,
make sure this command
```shell
git -C ~/.local/share/lunarvim/site/pack/packer/start/nvim-cmp rev-parse HEAD
```
outputs `b5433f901ebffc9e01b82ae13da9a92d49569205`
if it doesn't then force it using
```shell
git -C ~/.local/share/lunarvim/site/pack/packer/start/nvim-cmp pull
```

**Comment by thiagodebastos** [comment]
Thank you @abzcoding and @JCallicoat ! 🙌

**Comment by sangdth** [comment]
For those who has git issue like me (still don't know why)
```
You are not currently on a branch.
Please specify which branch you want to merge with.
```

Try this from `@bste`
```
Try to cd ~/.local/share/lunarvim/site/pack/packer/start/nvim-cmp and then git checkout main && git pull  and check that the commit hash is the one from the GH issue above.
```

It works for me.

**Comment by guedesfelipe** [comment]
Same here, and I don't have `~/.local/share/lunarvim/site/`
