### ISSUE TITLE
Freeze on window commands <C-w>

### ISSUE THREAD

**Issue by amoebaguy** [LunarVim/LunarVim#2552]
### Problem description

When issuing a window command, nvim freezes with 100% core usage until `<C-c>` when it becomes responsive again and reports:
  
    E5108: Error executing lua Keyboard interrupt
    stack traceback:
            [C]: in function 'getchar'
            ...te/pack/packer/opt/which-key.nvim/lua/which-key/view.lua:66: in function 'read_pending'
            ...te/pack/packer/opt/which-key.nvim/lua/which-key/view.lua:248: in function 'on_keys'
            ...te/pack/packer/opt/which-key.nvim/lua/which-key/view.lua:240: in function 'open'
            ...te/pack/packer/opt/which-key.nvim/lua/which-key/init.lua:51: in function 'show'
            [string ":lua"]:1: in main chunk

Applying https://github.com/folke/which-key.nvim/pull/275 to which-key fixes the issue.

### LunarVim version

commit a68c1cf

### Neovim version (>= 0.7)

NVIM v0.8.0-dev+95-g07660193a Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Operating system/version

Fedora Linux 35

### Relevant log output

```shell
-
```

**Comment by danielyrovas** [comment]
same here on NVIM v0.8.0-dev+100-g371dfb174 (ArchLinux)

**Comment by abzcoding** [comment]
this should be fixed via #2544

**Comment by mrdog233o5** [comment]
its still happening, am running lunarvim on macos, warp term emu, zsh terminal
