### ISSUE TITLE
Getting a failed to spawn command codespell: EACCES: permission denied

### ISSUE THREAD

**Issue by yudhiesh** [LunarVim/LunarVim#3086]
### Problem description

1. Enter a `.py` file
2. This error is thrown on startup `[null-ls] failed to run generator: ...site/pack/packer/start/null-ls.nvim/lua/null-ls/loop.lua:157: failed to spawn command codespell: EACCES: permission denied`

For some reason it causes my LSP not to work as expected, I get very basic autocompletion and I can't use any of the go-to statements such as go-to definitions. 

### LunarVim version

master-e4a5fe9

### Neovim version (>= 0.7.2)

NVIM v0.8.0-dev-1160-gb0fcdf9f0-dirty

### Operating system/version

macOS 11.6.8 (20G730)

### Steps to reproduce

This is my current [config.lua](https://github.com/yudhiesh/Vim-Stuff/blob/master/config.lua)

### support info

```console
 Use [q] or [Esc] to quit the window
 
 Language client log: /Users/yravindranath/.local/state/nvim/lsp.log
 Detected filetype:   python
 
 2 client(s) attached to this buffer: 
 
 Client: pyright (id: 1, pid: nil, bufnr: [4])
 	filetypes:       python
 	autostart:       true
 	root directory:  /Users/yravindranath
 	cmd:             pyright-langserver --stdio
 
 Client: null-ls (id: 2, pid: 5001, bufnr: [4])
 	filetypes:       python, typescript, typescriptreact, sh, javascript
 	autostart:       false
 	root directory:  /Users/yravindranath/metaflow_watcher/overseer
 	cmd:             nvim
 
 1 active client(s) not attached to this buffer: 
 
 Client: sumneko_lua (id: 3, pid: nil, bufnr: [23])
 	filetypes:       lua
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             lua-language-server
 
 Configured servers list: pyright, sumneko_lua
```

```console

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                python
* bufnr:                   4
* treesitter status:       active

Active client(s)
* name:                      pyright
* id:                        1
* supported filetype(s):     python
* attached buffers:          4
* root_dir pattern:          4
* capabilities:              callHierarchyProvider
* name:                      sumneko_lua
* id:                        3
* supported filetype(s):     lua
* attached buffers:          23
* root_dir pattern:          23
* capabilities:              documentRangeFormattingProvider | documentSymbolProvider | workspaceSymbolProvider
                             documentFormattingProvider      | referencesProvider     | hoverProvider
                             foldingRangeProvider            | definitionProvider     | colorProvider
                             documentHighlightProvider       | typeDefinitionProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels]

Formatters info
* Active: black  , isort  
* Supported: [autopep8, black, blue, isort, reorder_python_imports, usort, yapf]

Linters info
* Active: flake8  
* Supported: [flake8, mypy, pycodestyle, pydocstyle, pylama, pylint, pyproject_flake8, semgrep, vulture]

Code actions info
* Active: 
```

**Comment by abzcoding** [comment]
it seems like your `codespell` requires admin privileges or sth
https://github.com/yudhiesh/Vim-Stuff/blob/29f3147d5c935abefa8c31da1c602c34bea04ba2/config.lua#L183

**Comment by yudhiesh** [comment]
> it seems like your `codespell` requires admin privileges or sth https://github.com/yudhiesh/Vim-Stuff/blob/29f3147d5c935abefa8c31da1c602c34bea04ba2/config.lua#L183

I removed it and reset the cache, the error is gone now. But the code completion is still not working. 
<img width="1044" alt="Screenshot 2022-09-27 at 8 45 51 PM" src="https://user-images.githubusercontent.com/55042754/192529986-2c5c0a55-7dca-4073-b68a-67ae4fb342a9.png">

**Comment by abzcoding** [comment]
> > it seems like your `codespell` requires admin privileges or sth https://github.com/yudhiesh/Vim-Stuff/blob/29f3147d5c935abefa8c31da1c602c34bea04ba2/config.lua#L183
> 
> I removed it and reset the cache, the error is gone now. But the code completion is still not working. <img alt="Screenshot 2022-09-27 at 8 45 51 PM" width="1044" src="https://user-images.githubusercontent.com/55042754/192529986-2c5c0a55-7dca-4073-b68a-67ae4fb342a9.png">

can you run `:LvimInfo` on that file?

**Comment by yudhiesh** [comment]
> > I removed it and reset the cache, the error is gone now. But the code completion is still not working.
> 
> can you run `:LvimInfo` on that file?

```console

    __                          _    ___         
   / /   __  ______  ____ _____| |  / (_)___ ___ 
  / /   / / / / __ \/ __ `/ ___/ | / / / __ `__ \
 / /___/ /_/ / / / / /_/ / /   | |/ / / / / / / /
/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/ 


Buffer info
* filetype:                lua
* bufnr:                   18
* treesitter status:       active

Active client(s)
* name:                      pyright
* id:                        1
* supported filetype(s):     python
* attached buffers:          4
* root_dir pattern:          4
* capabilities:              callHierarchyProvider
* name:                      sumneko_lua
* id:                        3
* supported filetype(s):     lua
* attached buffers:          18
* root_dir pattern:          18
* capabilities:              typeDefinitionProvider | foldingRangeProvider            | documentFormattingProvider
                             definitionProvider     | documentRangeFormattingProvider | referencesProvider
                             colorProvider          | workspaceSymbolProvider         | documentSymbolProvider
                             hoverProvider          | documentHighlightProvider

Automatic LSP info
* Skipped servers: [angularls, ansiblels, csharp_ls, cssmodules_ls, denols, ember, emmet_ls, eslint, golangci_lint_ls, graphql, jedi_language_server, ltex, phpactor, psalm, pylsp, quick_lint_js, rome, reason_ls, solang, sorbet, sourcery, sqlls, sqls, stylelint_lsp, tflint, svlangserver, verible, vuels]

Formatters info
* Active: 
* Supported: [lua_format, stylua]

Linters info
* Active: 
* Supported: [luacheck, selene]

Code actions info
* Active: 
```

**Comment by abzcoding** [comment]
can you check ` ~/.local/state/nvim/lsp.log` for any errors?

**Comment by abzcoding** [comment]
also can you please close any other file and just do this:
```cmd
mkdir /tmp/test
cd /tmp/test
git init
lvim main.py
```
and see what works and what doesn't

**Comment by yudhiesh** [comment]
> ~/.local/state/nvim/lsp.log
Seems that there were some errors earlier from the `terraform-ls` but none for pyright. 
```console
[ERROR][2022-09-27 09:24:21] .../vim/lsp/rpc.lua:733	"rpc"	"terraform-ls"	"stderr"	'2022/09/27 09:24:21 jobs.go:380: JOBS: Finishing job "2008": "OpTypeLoadModuleMetadata" for {"file:///Users/yravindranath/infrastructure/ai-test/ec2/spark-client"} (err = %!s(<nil>), deferredJobs: [])\n'
[ERROR][2022-09-27 09:24:21] .../vim/lsp/rpc.lua:733	"rpc"	"terraform-ls"	"stderr"	'2022/09/27 09:24:21 jobs.go:265: JOBS: Dispatching next job "2009" (scheduler prio: -1, job prio: 0, isDirOpen: false): "OpTypeParseVariables" for {"file:///Users/yravindranath/infrastructure/ai-test/ec2/spark-client"}\n2022/09/27 09:24:21 opts.go:218: Received request batch of size 1 (qlen=40)\n2022/09/27 09:24:21 jobs.go:380: JOBS: Finishing job "2009": "OpTypeParseVariables" for {"file:///Users/yravindranath/infrastructure/ai-test/ec2/spark-client"} (err = %!s(<nil>), deferredJobs: [])\n2022/09/27 09:24:21 jobs.go:265: JOBS: Dispatching next job "201" (scheduler prio: -1, job prio: 0, isDirOpen: false): "OpTypeParseModuleConfiguration" for {"file:///Users/yravindranath/infrastructure/ai/eks/prod-eks-fgen-ai/1-helm"}\n2022/09/27 09:24:21 jobs.go:380: JOBS: Finishing job "201": "OpTypeParseModuleConfiguration" for {"file:///Users/yravindranath/infrastructure/ai/eks/prod-eks-fgen-ai/1-helm"} (err = %!s(<nil>), deferredJobs: [])\n2022/09/27 09:24:21 jobs.go:265: JOBS: Dispatching next job "2010" (scheduler prio: -1, job prio: 0, isDirOpen: false): "OpTypeDecodeVarsReferences" for {"file:///Users/yravindranath/infrastructure/ai-test/ec2/spark-client"}\n2022/09/27 09:24:21 jobs.go:380: JOBS: Finishing job "2010": "OpTypeDecodeVarsReferences" for {"file:///Users/yravindranath/infrastructure/ai-test/ec2/spark-client"} (err = %!s(<nil>), deferredJobs: [])\n2022/09/27 09:24:21 jobs.go:265: JOBS: Dispatching next job "2011" (scheduler prio: -1, job prio: 0, isDirOpen: false): "OpTypeDecodeReferenceTargets" for {"file:///Users/yravindranath/infrastructure/ai-test/ec2/spark-client"}\n2022/09/27 09:24:21 provider_schema.go:265: PSS: getting provider schema (/Users/yravindranath/infrastructure/ai-test/ec2/spark-client, registry.terraform.io/-/aws, ~> 3.0)\n2022/09/27 09:24:21 provider_schema.go:265: PSS: getting provider schema (/Users/yravindranath/infrastructure/ai-test/ec2/spark-client, registry.terraform.io/-/terraform, )\n2022/09/27 09:24:21 provider_schema.go:265: PSS: getting provider schema (/Users/yravindranath/infrastructure/ai-test/ec2/spark-client, terraform.io/builtin/terraform, )\n2022/09/27 09:24:21 provider_schema.go:265: PSS: getting provider schema (/Users/yravindranath/infrastructure/ai-test/ec2/spark-client, registry.terraform.io/-/template, )\n'
[START][2022-09-27 09:25:49] LSP logging initiated
[WARN][2022-09-27 09:25:49] .../lua/vim/lsp.lua:1072	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[START][2022-09-27 09:26:27] LSP logging initiated
[WARN][2022-09-27 09:26:27] ...lsp/handlers.lua:113	"The language server pyright triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2022-09-27 09:29:11] .../lua/vim/lsp.lua:1072	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[START][2022-09-27 09:35:12] LSP logging initiated
[WARN][2022-09-27 09:35:12] ...lsp/handlers.lua:113	"The language server pyright triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2022-09-27 20:39:11] LSP logging initiated
[WARN][2022-09-27 20:39:11] .../lua/vim/lsp.lua:1072	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[WARN][2022-09-27 20:39:29] ...lsp/handlers.lua:113	"The language server pyright triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2022-09-27 20:41:09] LSP logging initiated
[WARN][2022-09-27 20:41:09] .../lua/vim/lsp.lua:1072	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[START][2022-09-27 20:41:48] LSP logging initiated
[WARN][2022-09-27 20:41:48] ...lsp/handlers.lua:113	"The language server pyright triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2022-09-27 20:43:42] LSP logging initiated
[WARN][2022-09-27 20:43:42] ...lsp/handlers.lua:113	"The language server pyright triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2022-09-27 20:44:26] .../lua/vim/lsp.lua:1072	"server_request: no handler found for"	"workspace/diagnostic/refresh"
[START][2022-09-27 20:53:35] LSP logging initiated
[WARN][2022-09-27 20:53:35] ...lsp/handlers.lua:113	"The language server pyright triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2022-09-27 20:56:29] LSP logging initiated
[WARN][2022-09-27 20:56:29] ...lsp/handlers.lua:113	"The language server pyright triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2022-09-27 20:56:30] ...lsp/handlers.lua:487	"stubPath typings is not a valid directory."
[START][2022-09-27 20:57:40] LSP logging initiated
[WARN][2022-09-27 20:57:40] ...lsp/handlers.lua:113	"The language server pyright triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[START][2022-09-27 20:58:13] LSP logging initiated
[WARN][2022-09-27 20:58:13] ...lsp/handlers.lua:113	"The language server pyright triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2022-09-27 20:58:13] ...lsp/handlers.lua:487	"stubPath typings is not a valid directory."
```

**Comment by abzcoding** [comment]
ok let me grab your config and check it locally, brb

p.s: edited your comment to preserve your privacy

**Comment by yudhiesh** [comment]
> ok let me grab your config and check it locally, brb
> 
> p.s: edited your comment to preserve your privacy

Not facing the issue anymore in the tmp directory. But the problem still persists in my project repository.

**Comment by yudhiesh** [comment]
> > > ok let me grab your config and check it locally, brb
> > > p.s: edited your comment to preserve your privacy
> > 
> > 
> > Not facing the issue anymore in the tmp directory. But the problem still persists in my project repository.
> 
> is your project repo git managed or?

Yes

**Comment by abzcoding** [comment]
> > > > ok let me grab your config and check it locally, brb
> > > > p.s: edited your comment to preserve your privacy
> > > 
> > > 
> > > Not facing the issue anymore in the tmp directory. But the problem still persists in my project repository.
> > 
> > 
> > is your project repo git managed or?
> 
> Yes

and which branch of lunarvim are you on? `rolling` or `master`?
```shell
git -C ~/.local/share/lunarvim/lvim branch --show-current
```

**Comment by yudhiesh** [comment]
> git -C ~/.local/share/lunarvim/lvim branch --show-current

master

**Comment by yudhiesh** [comment]
I removed the repo and cloned it again but still the same issue.

**Comment by abzcoding** [comment]
first off make sure you are on the latest version of `master` using `:LvimUpdate`
or 
```shell
git -C ~/.local/share/lunarvim/lvim reset --hard
git -C ~/.local/share/lunarvim/lvim pull
```

then remove these lines from your config ( tokyonight and gitsigns)
https://github.com/yudhiesh/Vim-Stuff/blob/29f3147d5c935abefa8c31da1c602c34bea04ba2/config.lua#L191
https://github.com/yudhiesh/Vim-Stuff/blob/29f3147d5c935abefa8c31da1c602c34bea04ba2/config.lua#L197

since they are already included in lunarvim

**Comment by yudhiesh** [comment]
> first off make sure you are on the latest version of `master` using `:LvimUpdate` or
> 
> ```shell
> git -C ~/.local/share/lunarvim/lvim reset --hard
> git -C ~/.local/share/lunarvim/lvim pull
> ```
> 
> then remove these lines from your config ( tokyonight and gitsigns) https://github.com/yudhiesh/Vim-Stuff/blob/29f3147d5c935abefa8c31da1c602c34bea04ba2/config.lua#L191 https://github.com/yudhiesh/Vim-Stuff/blob/29f3147d5c935abefa8c31da1c602c34bea04ba2/config.lua#L197
> 
> since they are already included in lunarvim

Yes, it was already at the latest"LunarVim is already up-to-date". The issue still persists.

**Comment by abzcoding** [comment]
after doing those steps, (and maybe a `:PackerInstall`) you should be fine
<img width="500" alt="Screenshot 2022-09-27 at 4 43 37 PM (2)" src="https://user-images.githubusercontent.com/10992695/192536472-b4cdac69-5b9e-4dc4-b9cf-e0e68b0bff6d.png">

**Comment by abzcoding** [comment]
> Yes, it was already at the latest `"LunarVim is already up-to-date"`. Updated the config but the issue still persists.

hmm 🤔 that is very weird, since i just literally ran your config on a new linux machine and it worked

what is the output of this command?
```shell
git -C ~/.local/share/lunarvim/lvim rev-parse HEAD
```

**Comment by abzcoding** [comment]
> e4a5fe97abe500bbbe78fb137d57a59f558da05a

ok something is really wrong with your lunarvim installation 
lets do this:
```shell
rm -rf ~/.config/lvim/plugin
cd ~/.local/share/lunarvim/
rm -rf lvim
git clone https://github.com/LunarVim/LunarVim.git lvim
```
and then remove these lines from your `~/.config/lvim/config.lua`
```lua
  { "folke/tokyonight.nvim" },
  { "lewis6991/gitsigns.nvim" }
```
and reopen lvim and run `:PackerSync`

🤞 it should fix the issues

**Comment by abzcoding** [comment]
@yudhiesh make sure you are on the `rolling` branch

**Comment by yudhiesh** [comment]
> @yudhiesh make sure you are on the `rolling` branch

Yup, I did it on the rolling branch, but the issue still persists sadly. I am on this branch `de5691f2d56c79a9f630c27e6bb623a1638de949`.

**Comment by abzcoding** [comment]
> > @yudhiesh make sure you are on the `rolling` branch
> 
> Yup, I did it on the rolling branch, but the issue still persists sadly. I am on this branch `de5691f2d56c79a9f630c27e6bb623a1638de949`.

one more thing, does it work in new directories/projects ( like the temp one)
but not in your specific project or?

**Comment by yudhiesh** [comment]
> > > @yudhiesh make sure you are on the `rolling` branch
> > 
> > 
> > Yup, I did it on the rolling branch, but the issue still persists sadly. I am on this branch `de5691f2d56c79a9f630c27e6bb623a1638de949`.
> 
> one more thing, does it work in new directories/projects ( like the `/tmp` one) but not in your specific project or?

Its weird it's working in `tmp/test`.

**Comment by abzcoding** [comment]
> Strange I am getting a `[LSP][null-ls] timeout` error when saving the file.

that means one of your `formatter/linters` is taking more than a second to complete
you can raise that though

```lua
  format_on_save = {
    ---@usage pattern string pattern used for the autocommand (Default: '*')
    pattern = "*",
    ---@usage timeout number timeout in ms for the format request (Default: 1000)
    timeout = 5000, -- change this (default is 1000 which means 1 second)
    ---@usage filter func to select client
    filter = require("lvim.lsp.utils").format_filter,
  },

```

**Comment by yudhiesh** [comment]
> > Strange I am getting a `[LSP][null-ls] timeout` error when saving the file.
> 
> that means one of your `formatter/linters` is taking more than a second to complete you can raise that though
> 
> replace this line
> 
> https://github.com/yudhiesh/Vim-Stuff/blob/29f3147d5c935abefa8c31da1c602c34bea04ba2/config.lua#L13
> 
> with this
> 
> ```lua
> lvim.format_on_save = {
>     ---@usage pattern string pattern used for the autocommand (Default: '*')
>     pattern = "*",
>     ---@usage timeout number timeout in ms for the format request (Default: 1000)
>     timeout = 5000, -- change this (default is 1000 which means 1 second)
>     ---@usage filter func to select client
>     filter = require("lvim.lsp.utils").format_filter,
>   }
> ```

Ok not getting any timeouts now but the issue still persists.

**Comment by abzcoding** [comment]
So to recap, everything works outside of your project, but it doesn't inside it 🤯 


I can only think of project being big and language server taking a long time to index all of your stuff.
Which means it should work after a couple of seconds.

@kylo252 any idea what might cause this?

**Comment by yudhiesh** [comment]
> So to recap, everything works outside of your project, but it doesn't inside it 🤯
> 
> I can only think of project being big and language server taking a long time to index all of your stuff. Which means it should work after a couple of seconds.
> 
> @kylo252 any idea what might cause this?

That is correct, the thing is this isn't that big of a repo, it's just two microservices I maintain in a repository. I restarted my laptop and its still the same.

**Comment by yudhiesh** [comment]
> 

I also tried reverting back to the stable master branch, and after some time it started working again. But then I get these errors when in insert mode:
Error 1:
<img width="1536" alt="Screenshot 2022-09-28 at 9 36 18 AM" src="https://user-images.githubusercontent.com/55042754/192667518-1ed3ad7c-ff17-4af5-ba75-077697027b96.png">
Error 2:
<img width="1536" alt="Screenshot 2022-09-28 at 9 35 50 AM" src="https://user-images.githubusercontent.com/55042754/192667458-cdd92d49-bccb-4f4f-aafc-f5a9a2f4b093.png">

**Comment by kylo252** [comment]
are you sure you can install it manually? maybe `npm`  was never configured correctly for you

```shell
npm i -g codespell
```

**Comment by yudhiesh** [comment]
> are you sure you can install it manually? maybe `npm` was never configured correctly for you
> 
> ```shell
> npm i -g codespell
> ```

I tried that and I do not get the permission denied error anymore. Instead, I noticed something odd, when I am within a Python file all my CPU cores are being maxed out and `null-ls` throws a timeout even though I set the timeout to be 5 seconds as per [this example](https://github.com/LunarVim/LunarVim/issues/3086#issuecomment-1259518941).

I managed to get it to work by adding a `pyrightconfig.json` file in the root directory of my repository. Now it works again, but there is another issue. My CPU usage is constantly maxed out and others in [this thread](https://github.com/microsoft/pyright/issues/128) have the same problem which should have been fixed with the file I added. 

## HTOP while using LunarVim
<img width="1531" alt="Screenshot 2022-10-03 at 8 57 54 AM" src="https://user-images.githubusercontent.com/55042754/193484818-c3bb806b-f457-4075-8ecc-f0b4564f1c26.png">

## HTOP when I exited from LunarVim
<img width="1531" alt="Screenshot 2022-10-03 at 9 09 26 AM" src="https://user-images.githubusercontent.com/55042754/193485472-8b51b81d-3604-4dbf-bc29-503325b610ec.png">

**Comment by yudhiesh** [comment]
> > are you sure you can install it manually? maybe `npm` was never configured correctly for you
> > ```shell
> > npm i -g codespell
> > ```
> 
> I tried that and I do not get the permission denied error anymore. Instead, I noticed something odd, when I am within a Python file all my CPU cores are being maxed out and `null-ls` throws a timeout even though I set the timeout to be 5 seconds as per [this example](https://github.com/LunarVim/LunarVim/issues/3086#issuecomment-1259518941).
> 
> I managed to get it to work by adding a `pyrightconfig.json` file in the root directory of my repository. Now it works again, but there is another issue. My CPU usage is constantly maxed out and others in [this thread](https://github.com/microsoft/pyright/issues/128) have the same problem which should have been fixed with the file I added.
> ## HTOP while using LunarVim
> 
> <img alt="Screenshot 2022-10-03 at 8 57 54 AM" width="1531" src="https://user-images.githubusercontent.com/55042754/193484818-c3bb806b-f457-4075-8ecc-f0b4564f1c26.png">
> ## HTOP when I exited from LunarVim
> 
> <img alt="Screenshot 2022-10-03 at 9 09 26 AM" width="1531" src="https://user-images.githubusercontent.com/55042754/193485472-8b51b81d-3604-4dbf-bc29-503325b610ec.png">
> 
> Is there any way I can add a debounce on text changes to pyright within the configuration?

Removing `isort` from the config seems to solve the CPU usage issue.
